[build]
builder = "nixpacks"
buildCommand = "npx prisma generate && npx prisma db push && npm run build"

[deploy]
startCommand = "npm run start"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicy = "always"
